/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : desai
 * Created : 11/07/2014 01:38:32
 */

package main.com.desai.common;

public class Thing {

	private String name;

	/**
	 * getter method for name
	 * 
	 * @return
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 
	 * setter method for name
	 * 
	 * @param name
	 * 
	 */
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * toString method for Thing
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("Name :  " + this.name == null ? "" : this.name + ",");
		return "Thing [" + sb.toString() + "]";
	}

}
