/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : desai
 * Created : 11/07/2014 01:50:31
 */

package main.com.desai.common;



public class Vehicle {

	private String make;
	private String model;
	private Integer year;
	private String engine;

	/**
	 *
	 * getter method for make
	 * @return
	 *
	 */
	public String getMake() {
		return this.make;
	}

	/**
	 *
	 * setter method for make
	 * @param make
	 *
	 */
	public void setMake(final String make) {
		this.make = make;
	}

	/**
	 *
	 * getter method for model
	 * @return
	 *
	 */
	public String getModel() {
		return this.model;
	}

	/**
	 *
	 * setter method for model
	 * @param model
	 *
	 */
	public void setModel(final String model) {
		this.model = model;
	}

	/**
	 *
	 * getter method for year
	 * @return
	 *
	 */
	public Integer getYear() {
		return this.year;
	}

	/**
	 *
	 * getter method for engine
	 * @return
	 *
	 */
	public String getEngine() {
		return this.engine;
	}

	/**
	 *
	 * setter method for engine
	 * @param engine
	 *
	 */
	public void setEngine(final String engine) {
		this.engine = engine;
	}

	/**
	 *
	 * setter method for year
	 * @param year
	 *
	 */
	public void setYear(final Integer year) {
		this.year = year;
	}

	
}
